### ISSUE TITLE
Can you give me the PEPE asci file ? from your ufetch/neofetch

### ISSUE THREAD

**Issue by astrolemonade** [juacq97/dotfiles-lap#1]
![image](https://user-images.githubusercontent.com/35623921/59252800-89871f00-8c35-11e9-9a25-472fab1e808f.png)

**Comment by juacq97** [comment]
I don't have an ascii file (I copied that from a web page), but you can copy the acii picture from `scripts/ufetch-pepe`, it's just a shell script
